# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "dev-env-e4l"
  
  ENV['LC_ALL']="en_US.UTF-8"
  config.vm.network "forwarded_port", guest: 8083, host: 8086
  config.vm.network "private_network", ip: "192.168.56.93"
  config.vm.synced_folder "../data/shared", "/home/vagrant/shared"

  config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
    	  vb.cpus = 2
   end

  
   config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
  
    # Install default JRE for running Java applications
    sudo apt-get install default-jre -y
  
    # Install Node.js 15.14.0
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo gpg --dearmor -o /usr/share/keyrings/nodesource-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/nodesource-archive-keyring.gpg] https://deb.nodesource.com/node_15.x bionic main" | sudo tee /etc/apt/sources.list.d/nodesource.list
    echo "deb-src [signed-by=/usr/share/keyrings/nodesource-archive-keyring.gpg] https://deb.nodesource.com/node_15.x bionic main" | sudo tee -a /etc/apt/sources.list.d/nodesource.list
    sudo apt-get update
    sudo apt-get install -y nodejs
  
    sudo apt-get install --yes python
  
   SHELL
end  

